import { z } from 'zod'
import { ARCHETYPE_IDS, ARCHETYPES } from '@/lib/generation/archetypes'
import { HERO_VARIANTS, SECTION_TYPES } from '@/schemas/spec'

/**
 * Strategic hypotheses — candidate answers to "what should this page BE?".
 *
 * Generated by a model (stage ② hypothesize), judged by Jev (stage ③), then
 * turned into a blueprint by code. A hypothesis carries no copy: it is an
 * archetype, a narrative, a persuasion mechanism, a conversion approach and
 * an ordered list of sections, each with the job it does in the story.
 */

export const CONVERSION_APPROACHES = ['direct_action', 'free_trial', 'explore', 'contact'] as const
export type ConversionApproach = (typeof CONVERSION_APPROACHES)[number]

export const CONVERSION_LABELS: Record<ConversionApproach, string> = {
  direct_action: 'Ask for the core action immediately (buy, book, search, sign up)',
  free_trial: 'Offer a low-commitment trial or free tier first',
  explore: 'Invite browsing and discovery before the ask',
  contact: 'Ask the visitor to talk to a person',
}

export const hypothesisSection = z.object({
  type: z.enum(SECTION_TYPES),
  /** The job this section does in the narrative, e.g. "prove the fabric survives a season of trail runs". */
  purpose: z.string(),
  /** Essential sections are required; the composer may drop a non-essential one. */
  essential: z.boolean(),
})

/** What the hypothesizing model returns for one strategy. */
export const hypothesisDraft = z.object({
  name: z.string(),
  archetype: z.enum(ARCHETYPE_IDS),
  /** One sentence: why a page built this way will convert this audience. */
  thesis: z.string(),
  /** The persuasion mechanism: desire, proof, clarity, demonstration, risk reversal… */
  persuasion: z.string(),
  /** How the page frames the visitor: who they are and what they want. */
  audienceFraming: z.string(),
  /** The story beats, in order. */
  narrative: z.array(z.string()).min(3).max(7),
  hero: z.object({ variant: z.enum(HERO_VARIANTS), purpose: z.string() }),
  conversion: z.object({ approach: z.enum(CONVERSION_APPROACHES), rationale: z.string() }),
  sections: z.array(hypothesisSection).min(3).max(8),
})

export const hypothesisDraftSet = z.object({
  strategies: z.array(hypothesisDraft).min(3).max(5),
})

/** A hypothesis as the rest of the app sees it: a draft plus a stable id. */
export const strategyHypothesis = hypothesisDraft.extend({ id: z.string() })

export type HypothesisDraft = z.infer<typeof hypothesisDraft>
export type StrategyHypothesis = z.infer<typeof strategyHypothesis>
export type HypothesisSection = z.infer<typeof hypothesisSection>

/**
 * Structural problems with one strategy: sections or hero outside its
 * archetype's vocabulary, or the same section type used more than twice.
 * Empty means it can become a blueprint as written.
 */
export function hypothesisIssues(h: HypothesisDraft): string[] {
  const issues: string[] = []
  const archetype = ARCHETYPES[h.archetype]
  const allowed: readonly string[] = archetype.sections
  const heroes: readonly string[] = archetype.heroes

  if (!heroes.includes(h.hero.variant)) {
    issues.push(
      `"${h.name}": hero "${h.hero.variant}" is not available to ${h.archetype} (use one of ${heroes.join(', ')}).`,
    )
  }
  for (const s of h.sections) {
    if (!allowed.includes(s.type)) {
      issues.push(`"${h.name}": section "${s.type}" is not part of a ${h.archetype} page (allowed: ${allowed.join(', ')}).`)
    }
  }
  if (/^(strategy|option|candidate|approach)\s*[a-e1-5]?\s*$/i.test(h.name.trim())) {
    issues.push(`"${h.name}" is a label, not a name — name the strategy by its argument.`)
  }
  const counts = new Map<string, number>()
  for (const s of h.sections) counts.set(s.type, (counts.get(s.type) ?? 0) + 1)
  for (const [type, n] of counts) {
    if (n > 2) issues.push(`"${h.name}": "${type}" appears ${n} times; at most twice.`)
  }
  return issues
}

/** Candidates that differ only in copy are one candidate. */
export function sectionSignature(h: Pick<HypothesisDraft, 'hero' | 'sections'>): string {
  return [h.hero.variant, ...h.sections.map((s) => s.type)].join('>')
}

/* ------------------------------------------------------------------ */
/* Jev's judgment                                                      */
/* ------------------------------------------------------------------ */

export type RankedStrategy = { id: string; name: string; probability: number }

export type StrategyJudgment = {
  /** Combined distribution over the candidates, high → low. */
  ranked: RankedStrategy[]
  /** Jev's pick: rank 0 of `ranked`. */
  selected: string
  /** Each criterion Jev answered, with its own distribution over the candidates. */
  criteria: {
    id: string
    label: string
    weight: number
    confidence: number | null
    ranked: { id: string; probability: number }[]
  }[]
}
